version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hitalent_db
      POSTGRES_USER: hitalent_user
      POSTGRES_PASSWORD: Pythonn123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://hitalent_user:Pythonn123!@db:5432/hitalent_db
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: