"""добавил hired с типом date

Revision ID: 31547cfa5c9b
Revises: ea0e9c5e68bc
Create Date: 2026-03-13 22:09:24.433316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31547cfa5c9b'
down_revision: Union[str, Sequence[str], None] = 'ea0e9c5e68bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('hired_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'hired_at')
    # ### end Alembic commands ###
