"""model

Revision ID: 736551ac2c25
Revises: 0c7f2deeb9c2
Create Date: 2026-03-15 04:22:44.951173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736551ac2c25'
down_revision: Union[str, Sequence[str], None] = '0c7f2deeb9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_name_key'), 'departments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('departments_name_key'), 'departments', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
