"""ondelete=cascade

Revision ID: c2d7b71b30fb
Revises: 9af800ce2464
Create Date: 2026-03-13 22:44:12.842438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d7b71b30fb'
down_revision: Union[str, Sequence[str], None] = '9af800ce2464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_parent_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'departments', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_parent_id_fkey'), 'departments', 'departments', ['parent_id'], ['id'])
    # ### end Alembic commands ###
